"""
brand_names.py — Brand name → generic resolution
Compatible with the original RxGuard import: from brand_names import BRAND_TO_GENERIC, resolve_brand
Extended to include Indian trade names and combination drugs.
"""

BRAND_TO_GENERIC = {
    # === ANTIBIOTICS ===
    "augmentin":  {"generic":"amoxicillin clavulanate","display":"Amoxicillin+Clavulanate (Augmentin)","class":"Beta-lactam antibiotic","components":["amoxicillin","clavulanate"]},
    "mox":        {"generic":"amoxicillin","display":"Amoxicillin (Mox)","class":"Penicillin antibiotic","components":["amoxicillin"]},
    "azee":       {"generic":"azithromycin","display":"Azithromycin (Azee)","class":"Macrolide antibiotic","components":["azithromycin"]},
    "zithromax":  {"generic":"azithromycin","display":"Azithromycin (Zithromax)","class":"Macrolide antibiotic","components":["azithromycin"]},
    "ciplox":     {"generic":"ciprofloxacin","display":"Ciprofloxacin (Ciplox)","class":"Fluoroquinolone antibiotic","components":["ciprofloxacin"]},
    "cifran":     {"generic":"ciprofloxacin","display":"Ciprofloxacin (Cifran)","class":"Fluoroquinolone antibiotic","components":["ciprofloxacin"]},
    "taxim":      {"generic":"cefixime","display":"Cefixime (Taxim)","class":"Cephalosporin antibiotic","components":["cefixime"]},
    "suprax":     {"generic":"cefixime","display":"Cefixime (Suprax)","class":"Cephalosporin antibiotic","components":["cefixime"]},
    "sporidex":   {"generic":"cephalexin","display":"Cephalexin (Sporidex)","class":"Cephalosporin antibiotic","components":["cephalexin"]},
    "keflex":     {"generic":"cephalexin","display":"Cephalexin (Keflex)","class":"Cephalosporin antibiotic","components":["cephalexin"]},
    "metrogyl":   {"generic":"metronidazole","display":"Metronidazole (Metrogyl)","class":"Nitroimidazole antibiotic","components":["metronidazole"]},
    "flagyl":     {"generic":"metronidazole","display":"Metronidazole (Flagyl)","class":"Nitroimidazole antibiotic","components":["metronidazole"]},
    "doxlin":     {"generic":"doxycycline","display":"Doxycycline (Doxlin)","class":"Tetracycline antibiotic","components":["doxycycline"]},
    "vibramycin": {"generic":"doxycycline","display":"Doxycycline (Vibramycin)","class":"Tetracycline antibiotic","components":["doxycycline"]},
    "klacid":     {"generic":"clarithromycin","display":"Clarithromycin (Klacid)","class":"Macrolide antibiotic","components":["clarithromycin"]},
    "biaxin":     {"generic":"clarithromycin","display":"Clarithromycin (Biaxin)","class":"Macrolide antibiotic","components":["clarithromycin"]},
    "rcinex":     {"generic":"rifampicin isoniazid","display":"Rifampicin+INH (Rcinex)","class":"Antitubercular","components":["rifampicin","isoniazid"]},
    # === CARDIOVASCULAR ===
    "lipitor":    {"generic":"atorvastatin","display":"Atorvastatin (Lipitor)","class":"HMG-CoA reductase inhibitor","components":["atorvastatin"]},
    "storvas":    {"generic":"atorvastatin","display":"Atorvastatin (Storvas)","class":"HMG-CoA reductase inhibitor","components":["atorvastatin"]},
    "crestor":    {"generic":"rosuvastatin","display":"Rosuvastatin (Crestor)","class":"HMG-CoA reductase inhibitor","components":["rosuvastatin"]},
    "rozavel":    {"generic":"rosuvastatin","display":"Rosuvastatin (Rozavel)","class":"HMG-CoA reductase inhibitor","components":["rosuvastatin"]},
    "zocor":      {"generic":"simvastatin","display":"Simvastatin (Zocor)","class":"HMG-CoA reductase inhibitor","components":["simvastatin"]},
    "norvasc":    {"generic":"amlodipine","display":"Amlodipine (Norvasc)","class":"Calcium channel blocker","components":["amlodipine"]},
    "amlip":      {"generic":"amlodipine","display":"Amlodipine (Amlip)","class":"Calcium channel blocker","components":["amlodipine"]},
    "tenormin":   {"generic":"atenolol","display":"Atenolol (Tenormin)","class":"Beta-1 blocker","components":["atenolol"]},
    "atenol":     {"generic":"atenolol","display":"Atenolol (Atenol)","class":"Beta-1 blocker","components":["atenolol"]},
    "lopressor":  {"generic":"metoprolol","display":"Metoprolol (Lopressor)","class":"Beta-1 blocker","components":["metoprolol"]},
    "metolar":    {"generic":"metoprolol","display":"Metoprolol (Metolar)","class":"Beta-1 blocker","components":["metoprolol"]},
    "concor":     {"generic":"bisoprolol","display":"Bisoprolol (Concor)","class":"Beta-1 blocker","components":["bisoprolol"]},
    "cardivas":   {"generic":"carvedilol","display":"Carvedilol (Cardivas)","class":"Alpha/Beta blocker","components":["carvedilol"]},
    "zestril":    {"generic":"lisinopril","display":"Lisinopril (Zestril)","class":"ACE inhibitor","components":["lisinopril"]},
    "listril":    {"generic":"lisinopril","display":"Lisinopril (Listril)","class":"ACE inhibitor","components":["lisinopril"]},
    "vasotec":    {"generic":"enalapril","display":"Enalapril (Vasotec)","class":"ACE inhibitor","components":["enalapril"]},
    "altace":     {"generic":"ramipril","display":"Ramipril (Altace)","class":"ACE inhibitor","components":["ramipril"]},
    "ramace":     {"generic":"ramipril","display":"Ramipril (Ramace)","class":"ACE inhibitor","components":["ramipril"]},
    "cozaar":     {"generic":"losartan","display":"Losartan (Cozaar)","class":"ARB","components":["losartan"]},
    "cosart":     {"generic":"losartan","display":"Losartan (Cosart)","class":"ARB","components":["losartan"]},
    "diovan":     {"generic":"valsartan","display":"Valsartan (Diovan)","class":"ARB","components":["valsartan"]},
    "micardis":   {"generic":"telmisartan","display":"Telmisartan (Micardis)","class":"ARB","components":["telmisartan"]},
    "telsar":     {"generic":"telmisartan","display":"Telmisartan (Telsar)","class":"ARB","components":["telmisartan"]},
    "olsar":      {"generic":"olmesartan","display":"Olmesartan (Olsar)","class":"ARB","components":["olmesartan"]},
    "coumadin":   {"generic":"warfarin","display":"Warfarin (Coumadin)","class":"Vitamin K antagonist","components":["warfarin"]},
    "plavix":     {"generic":"clopidogrel","display":"Clopidogrel (Plavix)","class":"Antiplatelet","components":["clopidogrel"]},
    "deplatt":    {"generic":"clopidogrel","display":"Clopidogrel (Deplatt)","class":"Antiplatelet","components":["clopidogrel"]},
    "ecosprin":   {"generic":"aspirin","display":"Aspirin (Ecosprin)","class":"Antiplatelet/NSAID","components":["aspirin"]},
    "xarelto":    {"generic":"rivaroxaban","display":"Rivaroxaban (Xarelto)","class":"Direct Xa inhibitor","components":["rivaroxaban"]},
    "eliquis":    {"generic":"apixaban","display":"Apixaban (Eliquis)","class":"Direct Xa inhibitor","components":["apixaban"]},
    "lasix":      {"generic":"furosemide","display":"Furosemide (Lasix)","class":"Loop diuretic","components":["furosemide"]},
    "aldactone":  {"generic":"spironolactone","display":"Spironolactone (Aldactone)","class":"Aldosterone antagonist","components":["spironolactone"]},
    "digoxin":    {"generic":"digoxin","display":"Digoxin","class":"Cardiac glycoside","components":["digoxin"]},
    # === DIABETES ===
    "glucophage": {"generic":"metformin","display":"Metformin (Glucophage)","class":"Biguanide antidiabetic","components":["metformin"]},
    "glycomet":   {"generic":"metformin","display":"Metformin (Glycomet)","class":"Biguanide antidiabetic","components":["metformin"]},
    "obimet":     {"generic":"metformin","display":"Metformin (Obimet)","class":"Biguanide antidiabetic","components":["metformin"]},
    "amaryl":     {"generic":"glimepiride","display":"Glimepiride (Amaryl)","class":"Sulfonylurea","components":["glimepiride"]},
    "diamicron":  {"generic":"gliclazide","display":"Gliclazide (Diamicron)","class":"Sulfonylurea","components":["gliclazide"]},
    "gluconorm":  {"generic":"glipizide","display":"Glipizide (Gluconorm)","class":"Sulfonylurea","components":["glipizide"]},
    "januvia":    {"generic":"sitagliptin","display":"Sitagliptin (Januvia)","class":"DPP-4 inhibitor","components":["sitagliptin"]},
    "galvus":     {"generic":"vildagliptin","display":"Vildagliptin (Galvus)","class":"DPP-4 inhibitor","components":["vildagliptin"]},
    "jardiance":  {"generic":"empagliflozin","display":"Empagliflozin (Jardiance)","class":"SGLT-2 inhibitor","components":["empagliflozin"]},
    "farxiga":    {"generic":"dapagliflozin","display":"Dapagliflozin (Farxiga)","class":"SGLT-2 inhibitor","components":["dapagliflozin"]},
    "forxiga":    {"generic":"dapagliflozin","display":"Dapagliflozin (Forxiga)","class":"SGLT-2 inhibitor","components":["dapagliflozin"]},
    "victoza":    {"generic":"liraglutide","display":"Liraglutide (Victoza)","class":"GLP-1 agonist","components":["liraglutide"]},
    "ozempic":    {"generic":"semaglutide","display":"Semaglutide (Ozempic)","class":"GLP-1 agonist","components":["semaglutide"]},
    # === GI ===
    "omez":       {"generic":"omeprazole","display":"Omeprazole (Omez)","class":"Proton pump inhibitor","components":["omeprazole"]},
    "losec":      {"generic":"omeprazole","display":"Omeprazole (Losec)","class":"Proton pump inhibitor","components":["omeprazole"]},
    "pan":        {"generic":"pantoprazole","display":"Pantoprazole (Pan)","class":"Proton pump inhibitor","components":["pantoprazole"]},
    "pantocid":   {"generic":"pantoprazole","display":"Pantoprazole (Pantocid)","class":"Proton pump inhibitor","components":["pantoprazole"]},
    "nexpro":     {"generic":"esomeprazole","display":"Esomeprazole (Nexpro)","class":"Proton pump inhibitor","components":["esomeprazole"]},
    "nexium":     {"generic":"esomeprazole","display":"Esomeprazole (Nexium)","class":"Proton pump inhibitor","components":["esomeprazole"]},
    "rantac":     {"generic":"ranitidine","display":"Ranitidine (Rantac)","class":"H2 blocker","components":["ranitidine"]},
    "zantac":     {"generic":"ranitidine","display":"Ranitidine (Zantac)","class":"H2 blocker","components":["ranitidine"]},
    "pepcid":     {"generic":"famotidine","display":"Famotidine (Pepcid)","class":"H2 blocker","components":["famotidine"]},
    "ranidom":    {"generic":"domperidone","display":"Domperidone (Ranidom)","class":"Prokinetic","components":["domperidone"]},
    "motilium":   {"generic":"domperidone","display":"Domperidone (Motilium)","class":"Prokinetic","components":["domperidone"]},
    "emeset":     {"generic":"ondansetron","display":"Ondansetron (Emeset)","class":"5-HT3 antagonist","components":["ondansetron"]},
    "zofran":     {"generic":"ondansetron","display":"Ondansetron (Zofran)","class":"5-HT3 antagonist","components":["ondansetron"]},
    # === PAIN / CNS ===
    "combiflam":  {"generic":"ibuprofen paracetamol","display":"Ibuprofen+Paracetamol (Combiflam)","class":"NSAID + Analgesic","components":["ibuprofen","paracetamol"]},
    "dolo":       {"generic":"paracetamol","display":"Paracetamol (Dolo)","class":"Analgesic/Antipyretic","components":["paracetamol"]},
    "calpol":     {"generic":"paracetamol","display":"Paracetamol (Calpol)","class":"Analgesic/Antipyretic","components":["paracetamol"]},
    "tylenol":    {"generic":"paracetamol","display":"Paracetamol (Tylenol)","class":"Analgesic/Antipyretic","components":["paracetamol"]},
    "voveran":    {"generic":"diclofenac","display":"Diclofenac (Voveran)","class":"NSAID","components":["diclofenac"]},
    "voltaren":   {"generic":"diclofenac","display":"Diclofenac (Voltaren)","class":"NSAID","components":["diclofenac"]},
    "nurofen":    {"generic":"ibuprofen","display":"Ibuprofen (Nurofen)","class":"NSAID","components":["ibuprofen"]},
    "zerodol":    {"generic":"aceclofenac","display":"Aceclofenac (Zerodol)","class":"NSAID","components":["aceclofenac"]},
    "hifenac":    {"generic":"aceclofenac","display":"Aceclofenac (Hifenac)","class":"NSAID","components":["aceclofenac"]},
    "nicip":      {"generic":"nimesulide","display":"Nimesulide (Nicip)","class":"NSAID","components":["nimesulide"]},
    "ultram":     {"generic":"tramadol","display":"Tramadol (Ultram)","class":"Opioid analgesic","components":["tramadol"]},
    "tramacip":   {"generic":"tramadol","display":"Tramadol (Tramacip)","class":"Opioid analgesic","components":["tramadol"]},
    "lyrica":     {"generic":"pregabalin","display":"Pregabalin (Lyrica)","class":"Anticonvulsant/Neuropathic pain","components":["pregabalin"]},
    "neurontin":  {"generic":"gabapentin","display":"Gabapentin (Neurontin)","class":"Anticonvulsant","components":["gabapentin"]},
    "gabapin":    {"generic":"gabapentin","display":"Gabapentin (Gabapin)","class":"Anticonvulsant","components":["gabapentin"]},
    # === PSYCHIATRY ===
    "zoloft":     {"generic":"sertraline","display":"Sertraline (Zoloft)","class":"SSRI antidepressant","components":["sertraline"]},
    "serta":      {"generic":"sertraline","display":"Sertraline (Serta)","class":"SSRI antidepressant","components":["sertraline"]},
    "prozac":     {"generic":"fluoxetine","display":"Fluoxetine (Prozac)","class":"SSRI antidepressant","components":["fluoxetine"]},
    "lexapro":    {"generic":"escitalopram","display":"Escitalopram (Lexapro)","class":"SSRI antidepressant","components":["escitalopram"]},
    "cipralex":   {"generic":"escitalopram","display":"Escitalopram (Cipralex)","class":"SSRI antidepressant","components":["escitalopram"]},
    "efexor":     {"generic":"venlafaxine","display":"Venlafaxine (Efexor)","class":"SNRI antidepressant","components":["venlafaxine"]},
    "cymbalta":   {"generic":"duloxetine","display":"Duloxetine (Cymbalta)","class":"SNRI antidepressant","components":["duloxetine"]},
    "zyprexa":    {"generic":"olanzapine","display":"Olanzapine (Zyprexa)","class":"Atypical antipsychotic","components":["olanzapine"]},
    "risperdal":  {"generic":"risperidone","display":"Risperidone (Risperdal)","class":"Atypical antipsychotic","components":["risperidone"]},
    "seroquel":   {"generic":"quetiapine","display":"Quetiapine (Seroquel)","class":"Atypical antipsychotic","components":["quetiapine"]},
    "valium":     {"generic":"diazepam","display":"Diazepam (Valium)","class":"Benzodiazepine","components":["diazepam"]},
    "ativan":     {"generic":"lorazepam","display":"Lorazepam (Ativan)","class":"Benzodiazepine","components":["lorazepam"]},
    "xanax":      {"generic":"alprazolam","display":"Alprazolam (Xanax)","class":"Benzodiazepine","components":["alprazolam"]},
    # === THYROID ===
    "synthroid":  {"generic":"levothyroxine","display":"Levothyroxine (Synthroid)","class":"Thyroid hormone","components":["levothyroxine"]},
    "eltroxin":   {"generic":"levothyroxine","display":"Levothyroxine (Eltroxin)","class":"Thyroid hormone","components":["levothyroxine"]},
    # === ANTIFUNGALS ===
    "diflucan":   {"generic":"fluconazole","display":"Fluconazole (Diflucan)","class":"Azole antifungal","components":["fluconazole"]},
    "sporanox":   {"generic":"itraconazole","display":"Itraconazole (Sporanox)","class":"Azole antifungal","components":["itraconazole"]},
    # === RESPIRATORY ===
    "ventolin":   {"generic":"salbutamol","display":"Salbutamol (Ventolin)","class":"Beta-2 agonist (bronchodilator)","components":["salbutamol"]},
    "seretide":   {"generic":"salmeterol fluticasone","display":"Salmeterol+Fluticasone (Seretide)","class":"LABA+ICS combination","components":["salmeterol","fluticasone"]},
    "foracort":   {"generic":"formoterol budesonide","display":"Formoterol+Budesonide (Foracort)","class":"LABA+ICS combination","components":["formoterol","budesonide"]},
    "montek":     {"generic":"montelukast","display":"Montelukast (Montek)","class":"Leukotriene antagonist","components":["montelukast"]},
    "singulair":  {"generic":"montelukast","display":"Montelukast (Singulair)","class":"Leukotriene antagonist","components":["montelukast"]},
    "cetzine":    {"generic":"cetirizine","display":"Cetirizine (Cetzine)","class":"Antihistamine","components":["cetirizine"]},
    "allegra":    {"generic":"fexofenadine","display":"Fexofenadine (Allegra)","class":"Antihistamine","components":["fexofenadine"]},
    # === ANTIVIRALS ===
    "zovirax":    {"generic":"acyclovir","display":"Acyclovir (Zovirax)","class":"Antiviral","components":["acyclovir"]},
    "valtrex":    {"generic":"valacyclovir","display":"Valacyclovir (Valtrex)","class":"Antiviral","components":["valacyclovir"]},
    "tamiflu":    {"generic":"oseltamivir","display":"Oseltamivir (Tamiflu)","class":"Antiviral (neuraminidase inhibitor)","components":["oseltamivir"]},
    # === MISC ===
    "stugeron":   {"generic":"cinnarizine","display":"Cinnarizine (Stugeron)","class":"Antihistamine/antivertigo","components":["cinnarizine"]},
    "vertin":     {"generic":"betahistine","display":"Betahistine (Vertin)","class":"Histamine analogue (vertigo)","components":["betahistine"]},
    "aricept":    {"generic":"donepezil","display":"Donepezil (Aricept)","class":"Cholinesterase inhibitor","components":["donepezil"]},
    "namenda":    {"generic":"memantine","display":"Memantine (Namenda)","class":"NMDA antagonist","components":["memantine"]},
}

def resolve_brand(name):
    """Return generic info dict or None."""
    return BRAND_TO_GENERIC.get(name.lower().strip())
